### ISSUE TITLE
Add and event for pushFinish and pullFinish

### ISSUE THREAD

**Issue by schemedesigns** [timkelty/shipit-db#19]
I need to preform a search/replace on the db to update urls after push/pull. Currently there is only one event dbFinished so I am not able to determine if I need to perform the search/replace on local or remote.  Can events be added to the push/pull tasks?

**Comment by diggy** [comment]
You can parse the command line args to check if you're pushing or pulling:

```
var command = process.argv[2].split(":"),
    params  = process.argv[3].split(":"),
    push    = ("push" === params[1]);
```

**Comment by schemedesigns** [comment]
Thanks @diggy, that should work great!
