### ISSUE TITLE
if bzip2 not available, use gzip?

### ISSUE THREAD

**Issue by diggy** [timkelty/shipit-db#9]
I ran into an issue with a server where `bzip2` is not available (`bash: bunzip2: command not found`). Maybe a fallback mechanism using `gzip` could be provided? I hacked db.js and got things working with g(un)zip, but as I'm not really node-savvy, I'd rather leave it to the experts to implement this, if desired. In any case, it might be useful to put a small note in the readme about the requirement of `bzip2`.

**Comment by timkelty** [comment]
Yeah, sounds like a good idea.

**Comment by timkelty** [comment]
@diggy Sorry for dragging my feet here.

I just pushed some changes that allow users to override any of the shell commands via config.
Try it out: `npm install git+https://github.com/timkelty/shipit-db.git#master`

In your case, your shipit config would look something like this:

```
shipit.initConfig({
  default: {
    db: {
      ignoreTables: ['some_table'],
      shell: {
        unzip: function(file) {
          return util.format('bzip2 -d -f %s', file);
        }
      },
      local: {
        host     : 'localhost',
        adapter  : 'mysql',
        username : 'root',
        password : 'root',
        socket   : '/Applications/MAMP/tmp/mysql/mysql.sock',
        database : 'mysite_local',
      },
    }
  },
  staging: {
    servers: 'user@myserver.com',
    db: {
      remote: {
        host     : '127.0.0.1',
        adapter  : 'mysql',
        username : 'myusername',
        password : '123password',
        database : 'mysite_staging',
      }
    }
  }
});
```

You can do the same with: `shipit.config.db.shell.zip`, `shipit.config.db.shell.unzip`, `shipit.config.db.shell.load`, `shipit.config.db.shell.clean`. `this` is the `Shipit` instance in all cases.

Let me know if you get a chance to try it and I can publish a new version.

**Comment by diggy** [comment]
@timkelty Sorry it took so long to get back to you.

I just tested unzipping and it works great!

Maybe clarify in the docs that the function relies on the node.js `util` module?

```
var util = require('util');
```

**Comment by timkelty** [comment]
Yep I'll add that to the example.
That said, theres nothing _requiring_ you to use `util`. You just need to return the string, however you want to build it.

**Comment by travco** [comment]
Hi @diggy, if your issue is resolved, could you close it?

Thanks in advance!
